server:
  port: 8080
  servlet:
    content-path: /web
spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  thymeleaf:
    cache: false
    enable-spring-el-compiler: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sim_system?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true